com:
  cortzotinnus:
    security:
      web:
        config:
          token-duration-in-minutes: 30
          authorization-cookie-name: X-Authorization-token
          cookie-http-only: false
          use-cookie: false
          header-authorization-name: Authorization
          header-authorization-prefix: Bearer
        cors:
          allowed-origins: '*'
          allowed-methods:
            - GET
            - POST
            - PATCH
            - PUT
            - OPTIONS
          allowed-headers:
            - '*'
          allow-credentials: true
          register-cors-configuration-path: /**
        basic:
          enabled: true
          url-entry-point-pattern: /internal-api/**
          username: basic-auth-user
          password: clave
          roles:
            - ROLE_ADMIN
        token-authorization:
          enabled: true
          url-token-protected-pattern: /api/**
          excluded-urls:
            - /api/excluded/**
            - /api/token/refresh
        authentication:
          enabled: true
          login-processing-url: /api/auth/login
          logout-url: /api/auth/logout
          url-entry-point-pattern: /api/auth/**
    sample:
      firebase:
        firebase-key: Abckey
        url: https://www.googleapis.com
        resources: classpath:firebase/xyz-firebase-admin.json
        database-url: https://xyz.firebaseio.com/
      googleapis:
        base-url: https://www.googleapis.com